type Choice = { id: string; label: string; personId?: string; name?: string; avatarUrl?: string; timeline?: string[] };
type Question = { id: string; type: string; act: string; label: string; prompt: string; choices: Choice[]; correctChoice: string; evidence: { eyebrow: string; rows: string[][]; finding: string } };
type Player = { id: string; nickname: string; score: number; isBot: boolean };
type Room = { code: string; hostKey: string; phase: string; questionIndex: number; phaseStartedAt: number | null; phaseEndsAt: number | null; players: Player[]; answers: Record<number, Record<string, { choice: string; answeredAt: number; points: number }>>; settledQuestions: number[] };

const timings = { questionMs: 10_000, revealMs: 7_000, leaderboardMs: 3_000, botAnswerMs: 2_500 };

export const suspects = [
  { id: "rebecca", name: "Rebecca｜彭聿采", alias: "小吃帳本王", avatar: "B", avatarUrl: "/avatars/rebecca.png", avatarSource: "Jira", color: "#6dd7c7" },
  { id: "xu-ruiyu", name: "Rita｜徐瑞妤", alias: "超商地圖王", avatar: "R", avatarUrl: "/avatars/xu-ruiyu.png", avatarSource: "Jira", color: "#f5c451" },
  { id: "he-pinru", name: "Clark｜何品儒", alias: "速食巡查員", avatar: "C", avatarUrl: "/avatars/he-pinru.png", avatarSource: "Jira", color: "#ff6e56" },
  { id: "huang-junlin", name: "Neil｜黃俊霖", alias: "7-ELEVEN 地縛靈", avatar: "N", avatarUrl: "/avatars/huang-junlin.png", avatarSource: "Jira", color: "#a98cff" },
];

const p = (name: string, merchant: string, statement: string, truth: string, count: string, avatarUrl: string, id: string): Choice => ({ id, personId: id, name, avatarUrl, label: statement, timeline: merchant ? [merchant, truth, count] : undefined });

export const questions: Question[] = [
  { id:"q1", type:"merchant", act:"第一幕｜蒐集資訊", label:"破解商家", prompt:"模糊發票只剩「全聯實業…中和分公司」與總額 NT$ 1,687。這間店是哪個通路？", choices:[{id:"rtmart",label:"大潤發"},{id:"pxmart",label:"全聯"},{id:"carrefour",label:"家樂福"},{id:"costco",label:"好市多"}], correctChoice:"rtmart", evidence:{eyebrow:"CLUE DECODE 01",rows:[["模糊抬頭","全聯實業…中和分公司"],["通路解碼","大潤發"],["發票總額","NT$ 1,687"],["敏感欄位","已遮蔽"]],finding:"第一塊拼圖成立：商家是大潤發。法律登記名稱不等於大家熟悉的通路名稱。"}},
  { id:"q2", type:"item", act:"第一幕｜蒐集資訊", label:"猜測品名", prompt:"同筆發票還留下「除菌、噴霧、NT$ 99」三個碎片。真正品名是什麼？", choices:[{id:"febreze",label:"風倍清噴霧除菌"},{id:"yogurt",label:"福樂頂級無加糖優格"},{id:"table",label:"開桌服務"},{id:"milk",label:"瑞穗極製鮮乳"}], correctChoice:"febreze", evidence:{eyebrow:"CLUE DECODE 02",rows:[["品項","風倍清噴霧除菌"],["單價","NT$ 99"],["同筆品項","ARIEL 室內瓶"],["線索狀態","等待確認發票"]],finding:"第二塊拼圖成立：物品是風倍清噴霧除菌。先別猜犯人，必須把完整發票拼回來。"}},
  { id:"q3", type:"invoice", act:"第一幕｜蒐集資訊", label:"確認發票", prompt:"哪一組日期、商家與品項，能把這張模糊發票完整復原？", choices:[{id:"a",label:"6/15 → 大潤發 → 風倍清噴霧除菌"},{id:"b",label:"7/23 → 家樂福 → 無加糖優格"},{id:"c",label:"8/18 → 路易莎 → 開桌服務"},{id:"d",label:"5/24 → 大潤發 → 瑞穗鮮乳"}], correctChoice:"a", evidence:{eyebrow:"INVOICE CONFIRMED",rows:[["日期","2026/06/15"],["商家","大潤發"],["發票總額","NT$ 1,687"],["關鍵品項","風倍清噴霧除菌"]],finding:"資訊蒐集完成。日期、商家、金額與品項已確認；下一幕才開始審口供。"}},
  { id:"q4", type:"lie", act:"第二幕｜框出嫌疑人", label:"口供第 1 組", prompt:"三人各說一項消費習慣，只有一人在說謊。把他框進嫌疑區。", choices:[p("Robert｜邵士銓","","我三個月內造訪全家 13 次。","","","/avatars/robert.png","robert"),p("Michelle｜邱庭","","我三個月內造訪 7-ELEVEN 26 次。","","","/avatars/michelle.png","michelle"),p("Rebecca｜彭聿采","","我三個月內造訪全聯 18 次。","","","/avatars/rebecca.png","rebecca")], correctChoice:"rebecca", evidence:{eyebrow:"INTERROGATION 01",rows:[["說謊者","Rebecca｜彭聿采"],["她的口供","全聯 18 次"],["發票真相","全聯只有 6 次"],["處置","嫌疑人 1/4"]],finding:"Rebecca 的全聯紀錄實際只有 6 次。聚光燈鎖定，但說謊只代表進入嫌疑區，不等於定罪。"}},
  { id:"q5", type:"lie", act:"第二幕｜框出嫌疑人", label:"口供第 2 組", prompt:"第二組接受訊問：哪一位的數字經不起發票核對？", choices:[p("Rita｜徐瑞妤","","我三個月內只去全家 30 次。","","","/avatars/xu-ruiyu.png","xu-ruiyu"),p("Clark｜何品儒","","我三個月內造訪麥當勞 13 次。","","","/avatars/he-pinru.png","he-pinru"),p("Neil｜黃俊霖","","我三個月內造訪 7-ELEVEN 99 次。","","","/avatars/huang-junlin.png","huang-junlin")], correctChoice:"xu-ruiyu", evidence:{eyebrow:"INTERROGATION 02",rows:[["說謊者","Rita｜徐瑞妤"],["她的口供","全家 30 次"],["發票真相","全家高達 76 次"],["處置","嫌疑人 2/4"]],finding:"Rita 不是少去一點，是把 76 次說成 30 次。第二張嫌疑人檔案正式入列。"}},
  { id:"q6", type:"lie", act:"第二幕｜框出嫌疑人", label:"口供第 3 組", prompt:"第三組換位再問一次。誰把自己的消費頻率說小了？", choices:[p("Michelle｜邱庭","","我三個月內造訪 7-ELEVEN 26 次。","","","/avatars/michelle.png","michelle"),p("Clark｜何品儒","","我三個月內只吃麥當勞 3 次。","","","/avatars/he-pinru.png","he-pinru"),p("Robert｜邵士銓","","我三個月內造訪全家 13 次。","","","/avatars/robert.png","robert")], correctChoice:"he-pinru", evidence:{eyebrow:"INTERROGATION 03",rows:[["說謊者","Clark｜何品儒"],["他的口供","麥當勞 3 次"],["發票真相","麥當勞 13 次"],["處置","嫌疑人 3/4"]],finding:"Clark 少報了整整 10 次麥當勞。第三位嫌疑人被紅框送進最終名單。"}},
  { id:"q7", type:"lie", act:"第二幕｜框出嫌疑人", label:"口供第 4 組", prompt:"最後一組口供。誰的便利商店數字離真相最遠？", choices:[p("Rebecca｜彭聿采","","我三個月內造訪五竹餐飲 13 次。","","","/avatars/rebecca.png","rebecca"),p("Rita｜徐瑞妤","","我三個月內造訪全家 76 次。","","","/avatars/xu-ruiyu.png","xu-ruiyu"),p("Neil｜黃俊霖","","我三個月內只去 7-ELEVEN 49 次。","","","/avatars/huang-junlin.png","huang-junlin")], correctChoice:"huang-junlin", evidence:{eyebrow:"INTERROGATION 04",rows:[["說謊者","Neil｜黃俊霖"],["他的口供","7-ELEVEN 49 次"],["發票真相","7-ELEVEN 99 次"],["處置","嫌疑人 4/4"]],finding:"Neil 直接少報 50 次。四輪訊問結束：Rebecca、Rita、Clark、Neil 進入最終對決。"}},
  { id:"q8", type:"route", act:"第三幕｜找出犯人", label:"完整行動線", prompt:"把四名嫌疑人的完整消費軌跡攤開。哪條路線同時吻合大潤發、五竹與 SUBWAY？", choices:[p("Rebecca｜彭聿采","大潤發 2","大潤發 2 → 五竹 13 → SUBWAY 10","五竹 13","SUBWAY 10","/avatars/rebecca.png","rebecca"),p("Rita｜徐瑞妤","全家 76","全家 76 → 7-ELEVEN 46 → 健榮發 28","7-ELEVEN 46","健榮發 28","/avatars/xu-ruiyu.png","xu-ruiyu"),p("Clark｜何品儒","7-ELEVEN 30","7-ELEVEN 30 → 全家 14 → 麥當勞 13","全家 14","麥當勞 13","/avatars/he-pinru.png","he-pinru"),p("Neil｜黃俊霖","7-ELEVEN 99","7-ELEVEN 99 → Sukiya 8 → 全家 6","Sukiya 8","全家 6","/avatars/huang-junlin.png","huang-junlin")], correctChoice:"rebecca", evidence:{eyebrow:"ROUTE MATCHED",rows:[["軌跡物主","Rebecca｜彭聿采"],["大潤發","2 次"],["五竹餐飲","13 次"],["SUBWAY","10 次"]],finding:"四條路線只有 Rebecca 的消費輪廓與犯罪現場發票吻合。還差最後一步：把日期、商家、品項與物主鎖成證據鏈。"}},
  { id:"q9", type:"route", act:"第三幕｜找出犯人", label:"證據鏈結案", prompt:"哪一條消費行動線，能讓證據鏈完整閉合？", choices:[{id:"a",label:"6/15 購買 → 大潤發 → 風倍清 → Rebecca 發票"},{id:"b",label:"7/23 購買 → 家樂福 → 優格 → Michelle 發票"},{id:"c",label:"8/18 購買 → 路易莎 → 開桌 → Robert 發票"},{id:"d",label:"先猜犯人 → 再挑一張看起來合理的發票"}], correctChoice:"a", evidence:{eyebrow:"EVIDENCE CHAIN CLOSED",rows:[["遊戲犯人","Rebecca｜彭聿采"],["購買日期","2026/06/15"],["來源","大潤發"],["關鍵品項","風倍清噴霧除菌"]],finding:"證據鏈閉合：真實消費只證明購買紀錄；獎盃失竊、口供與犯人身分皆為遊戲虛構。"}},
];

const root = globalThis as typeof globalThis & { __invoiceDetectiveRooms?: Map<string, Room> };
const rooms = root.__invoiceDetectiveRooms ??= new Map<string, Room>();

function code() { for (let i=0;i<100;i+=1) { const value=String(Math.floor(1000+Math.random()*9000)); if(!rooms.has(value)) return value; } return String(Date.now()).slice(-4); }
function ranks(room: Room) { return room.players.map(({id,nickname,score,isBot})=>({id,nickname,score,isBot})).sort((a,b)=>b.score-a.score || a.nickname.localeCompare(b.nickname,"zh-Hant")); }
function begin(room: Room,index:number){room.questionIndex=index;room.phase="question";room.phaseStartedAt=Date.now();room.phaseEndsAt=room.phaseStartedAt+timings.questionMs;room.answers[index]={};}
function settle(room:Room){if(room.settledQuestions.includes(room.questionIndex))return;const q=questions[room.questionIndex];const answers=room.answers[room.questionIndex]??{};for(const player of room.players){const a=answers[player.id];if(a?.choice===q.correctChoice)player.score+=a.points;}room.settledQuestions.push(room.questionIndex);room.phase="reveal";room.phaseStartedAt=Date.now();room.phaseEndsAt=room.phaseStartedAt+timings.revealMs;}
function sync(room:Room){const now=Date.now();if(room.phase==="question"){const q=questions[room.questionIndex];const answers=room.answers[room.questionIndex]??{};if(room.phaseStartedAt&&now-room.phaseStartedAt>=timings.botAnswerMs){room.players.filter(x=>x.isBot&&!answers[x.id]).forEach((player,index)=>{const ids=q.choices.map(x=>x.id);const choice=(room.questionIndex+index)%4===0?ids[(ids.indexOf(q.correctChoice)+1)%ids.length]:q.correctChoice;answers[player.id]={choice,answeredAt:now,points:choice===q.correctChoice?125:0};});}if((room.phaseEndsAt&&now>=room.phaseEndsAt)||(room.players.length>0&&Object.keys(answers).length>=room.players.length))settle(room);}else if(room.phase==="reveal"&&room.phaseEndsAt&&now>=room.phaseEndsAt){room.phase="leaderboard";room.phaseStartedAt=now;room.phaseEndsAt=now+timings.leaderboardMs;}else if(room.phase==="leaderboard"&&room.phaseEndsAt&&now>=room.phaseEndsAt){if(room.questionIndex+1>=questions.length){room.phase="results";room.phaseStartedAt=now;room.phaseEndsAt=null;}else begin(room,room.questionIndex+1);}}

export function createRoom(){const room:Room={code:code(),hostKey:crypto.randomUUID(),phase:"lobby",questionIndex:-1,phaseStartedAt:null,phaseEndsAt:null,players:[],answers:{},settledQuestions:[]};rooms.set(room.code,room);return{room:publicRoom(room,{hostKey:room.hostKey}),hostKey:room.hostKey};}
export function findRoom(roomCode:string){const room=rooms.get(roomCode);if(!room)throw Object.assign(new Error("case_not_found"),{status:404});sync(room);return room;}

export function publicRoom(room:Room,viewer:{playerKey?:string|null;hostKey?:string|null}={}){const current=room.questionIndex>=0?questions[room.questionIndex]:null;const reveal=["reveal","leaderboard","results"].includes(room.phase);const answers=room.answers[room.questionIndex]??{};const board=ranks(room);const total=room.settledQuestions.reduce((n,i)=>n+Object.keys(room.answers[i]??{}).length,0);const correct=room.settledQuestions.reduce((n,i)=>n+Object.values(room.answers[i]??{}).filter(a=>a.choice===questions[i].correctChoice).length,0);return{code:room.code,phase:room.phase,questionIndex:room.questionIndex,questionCount:questions.length,phaseStartedAt:room.phaseStartedAt,phaseEndsAt:room.phaseEndsAt,suspects,players:room.players,leaderboard:board,answeredCount:Object.keys(answers).length,viewerAnswered:Boolean(viewer.playerKey&&answers[viewer.playerKey]),viewerChoice:viewer.playerKey?answers[viewer.playerKey]?.choice??null:null,isHost:Boolean(viewer.hostKey&&viewer.hostKey===room.hostKey),question:current?{id:current.id,type:current.type,act:current.act,label:current.label,prompt:current.prompt,choices:current.choices,...(reveal?{correctChoice:current.correctChoice,evidence:current.evidence,distribution:Object.fromEntries(current.choices.map(c=>[c.id,Object.values(answers).filter(a=>a.choice===c.id).length]))}:{})}:null,results:room.phase==="results"?{champion:board[0]??null,accuracy:total?Math.round(correct/total*100):0,totalAnswers:total,culprit:"Rebecca｜彭聿采",culpritId:"rebecca",culpritPortrait:"/avatars/rebecca.png",finalSuspects:suspects,evidenceChain:["6/15 購買","大潤發","風倍清噴霧除菌","Rebecca 的發票"],caseFinding:"發票證明了購買紀錄；202 獎盃失竊、口供與犯人身分皆為遊戲虛構。",needPyramid:[{level:"自我實現",value:"看懂自己的消費模式，選一件想改變的小事"},{level:"尊重",value:"用推理勳章肯定觀察力，不用消費羞辱任何人"},{level:"愛與歸屬",value:"三人互證、全場投票、十秒本人補充，創造共同笑點"},{level:"安全",value:"本人同意、敏感欄位遮蔽，案情與定罪皆標示為遊戲虛構"},{level:"生理",value:"從吃飯、喝水、便利商店等日常生存消費切入"}]}:null};}

export function roomGet(roomCode:string,viewer:Record<string,string|null>){return publicRoom(findRoom(roomCode),viewer);}
export function roomAction(roomCode:string,action:string,body:Record<string,string>){const room=findRoom(roomCode);if(action==="join"){if(room.phase!=="lobby")throw Object.assign(new Error("case_already_started"),{status:409});const nickname=String(body.nickname??"").trim().replace(/\s+/g," ").slice(0,16);if(nickname.length<2)throw Object.assign(new Error("nickname_too_short"),{status:400});if(room.players.some(p=>p.nickname.toLowerCase()===nickname.toLowerCase()))throw Object.assign(new Error("nickname_taken"),{status:409});const player={id:crypto.randomUUID(),nickname,score:0,isBot:false};room.players.push(player);return{status:201,body:{playerKey:player.id,room:publicRoom(room,{playerKey:player.id})}};}if(body.hostKey!==room.hostKey)throw Object.assign(new Error("host_required"),{status:403});if(action==="fill"){const names=["餅乾警探","手搖線民","宵夜目擊者","發票小精靈","冰箱鑑識官","週末美食家"];while(room.players.length<6){const nickname=names.find(n=>!room.players.some(p=>p.nickname===n))??`示範偵探 ${room.players.length+1}`;room.players.push({id:crypto.randomUUID(),nickname,score:0,isBot:true});}}else if(action==="start"){if(room.players.length<4)throw Object.assign(new Error("need_four_detectives"),{status:409});begin(room,0);}else if(action==="advance"){if(room.phase==="question")settle(room);else if(room.phase==="reveal"){room.phase="leaderboard";room.phaseStartedAt=Date.now();room.phaseEndsAt=room.phaseStartedAt+timings.leaderboardMs;}else if(room.phase==="leaderboard"){if(room.questionIndex+1>=questions.length){room.phase="results";room.phaseEndsAt=null;}else begin(room,room.questionIndex+1);}}else if(action==="reset"){room.phase="lobby";room.questionIndex=-1;room.phaseStartedAt=null;room.phaseEndsAt=null;room.answers={};room.settledQuestions=[];room.players.forEach(p=>p.score=0);}else if(action==="answer"){throw Object.assign(new Error("player_required"),{status:403});}return{status:200,body:publicRoom(room,{hostKey:body.hostKey})};}

export function answerRoom(roomCode:string,body:Record<string,string>){const room=findRoom(roomCode);if(room.phase!=="question")throw Object.assign(new Error("answering_closed"),{status:409});const player=room.players.find(p=>p.id===body.playerKey&&!p.isBot);if(!player)throw Object.assign(new Error("player_required"),{status:403});const q=questions[room.questionIndex];if(!q.choices.some(c=>c.id===body.choice))throw Object.assign(new Error("invalid_choice"),{status:400});const answers=room.answers[room.questionIndex]??{};if(answers[player.id])throw Object.assign(new Error("answer_locked"),{status:409});const secondsLeft=Math.max(0,Math.ceil(((room.phaseEndsAt??Date.now())-Date.now())/1000));answers[player.id]={choice:body.choice,answeredAt:Date.now(),points:body.choice===q.correctChoice?100+secondsLeft*5:0};room.answers[room.questionIndex]=answers;sync(room);return publicRoom(room,{playerKey:player.id});}
